# argocd-apps/monitoring/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

# Just deploy your local resources
resources:
  - namespace.yaml
  - ingress.yaml
  - helm-application.yaml  # New file that defines the Helm deployment

# Common labels
commonLabels:
  app.kubernetes.io/part-of: data-platform
  app.kubernetes.io/managed-by: argocd