apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgresql

resources:
  - namespace.yaml
  #- postgresql-backup-pvc.yaml  # for backups
  #- network-policy.yaml         # for network security
  #- backup-cronjob.yaml         # for scheduled backups

commonLabels:
  app.kubernetes.io/part-of: data-platform
  app.kubernetes.io/managed-by: argocd