apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # Adjust based on your storage class
  resources:
    requests:
      storage: 100Gi  # Adjust size as needed