apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: minio
type: Opaque
stringData:
  accesskey: "minioadmin"  # Change in production
  secretkey: "minioadmin123"  # Change in production