# Dremio Enterprise Values for Kubernetes
# Reference: https://docs.dremio.com/current/admin/deployment/kubernetes/

# Dremio Image
image:
  repository: quay.io/dremio/dremio-enterprise
  tag: 26.0.1
  pullPolicy: IfNotPresent

# Image Pull Secrets
imagePullSecrets:
- name: dremio-image-pull-secret

# Dremio License
license:
  value: "eyJraWQiOiI4MGZhMjgxYzZhZjczNDNkNTE1YTVhMzg1MDg1N2RhNmE2YmEzMTU3NWE5ZjVlZmVhMmQ4MTkyMGUyM2Q2OGY0IiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJEcmVtaW8iLCJzdWIiOiIwMDM1ZDAwMDA3TFRkT0VBQTEiLCJuYmYiOjE3NTI3ODA0NzYsImV4cCI6MTc1NTU0NTI3NiwiaWF0IjoxNzUyNzgwNDc2LCJqdGkiOiIxNzUyNzgwNDc2MDYyVzJjciJ9.u8bxfpQvyieeGn3H8RNIyKqbIgHR4pYO0mfBDBh23WJJw58t2WsDEhbOL6rUdfyGu4hItUtcohCoSEXMaAAolg"

# Service Account
serviceAccount:
  create: true
  name: dremio

# Dremio Coordinator
coordinator:
  count: 1
  memory: 8192
  cpu: 2
  
  web:
    port: 9047
    ssl:
      enabled: false
  
  client:
    port: 31010
  
  flight:
    port: 32010
    
  fabric:
    port: 45678
    
  cloudCache:
    enabled: false
    
  extraInitContainers: ""
  
  extraVolumes: []
  extraVolumeMounts: []
  
  # Volume claim template for coordinator
  storageClass: gp2
  volumeSize: 50Gi

# Dremio Executor
executor:
  count: 1
  memory: 8192
  cpu: 2
  
  engines: 1
  
  cloudCache:
    enabled: false
    volumes:
    - size: 100Gi
    
  extraInitContainers: ""
  
  extraVolumes: []
  extraVolumeMounts: []
  
  # Volume claim template for executors
  storageClass: gp2
  volumeSize: 50Gi

# Zookeeper
zookeeper:
  enabled: true
  count: 1
  memory: 1024
  cpu: 0.5
  storageClass: gp2
  volumeSize: 10Gi

# Distributed Storage
distStorage:
  type: "local"
  
  # For AWS S3
  # type: "aws"
  # aws:
  #   bucketName: "dremio-bucket"
  #   path: "/"
  #   authentication: "instanceMetadata"
  #   credentials:
  #     accessKey: ""
  #     secret: ""

# Service Type
service:
  type: ClusterIP
  sessionAffinity: ClientIP

# Ingress
ingress:
  enabled: false
  class: nginx
  annotations: {}

# Annotations
annotations: {}
podAnnotations: {}

# Tolerations
tolerations: []

# Node Selector
nodeSelector: {}

# Labels
labels: {}
podLabels: {}

# DremioAdmin
admin:
  username: admin
  firstName: Admin
  lastName: User
  email: admin@dremio.com

# Extra Startup Params
extraStartupParams: ""

# Extra Env Variables
extraEnvVars: []

# TLS
tls:
  enabled: false
  
# Resources
resources:
  coordinator:
    memory:
      requests: 8Gi
      limits: 16Gi
    cpu:
      requests: 2
      limits: 4
  executor:
    memory:
      requests: 8Gi
      limits: 16Gi
    cpu:
      requests: 2
      limits: 4
  zookeeper:
    memory:
      requests: 1Gi
      limits: 2Gi
    cpu:
      requests: 0.5
      limits: 1