# Spark Operator Configuration for Data Platform

# FIXED: Correct image repository and tag
image:
  repository: gcr.io/spark-operator/spark-operator  # FIXED: Added -operator suffix
  tag: v1beta2-1.3.8-3.1.1
  pullPolicy: IfNotPresent

# Spark job namespace (where Spark applications will run)
sparkJobNamespace: spark

# Enable webhook for validation
webhook:
  enable: false  # Disabled initially for easier deployment
  port: 8080
  namespaceSelector: |
    matchLabels:
      spark-webhook: enabled

# Resource quotas and limits
resourceQuotaEnforcement:
  enable: false

# Controller settings
controllerThreads: 10
resyncInterval: 30

# Enable batch scheduler
batchScheduler:
  enable: false

# Metrics configuration
metrics:
  enable: true
  port: 10254
  endpoint: /metrics
  prefix: ""

# Service Accounts
serviceAccounts:
  spark:
    create: true
    name: spark
  sparkoperator:
    create: true
    name: spark-operator

# RBAC
rbac:
  create: true
  createRole: true
  createClusterRole: true

# Resources for the operator pod
resources:
  requests:
    cpu: 100m
    memory: 300Mi
  limits:
    cpu: 200m
    memory: 500Mi

# Node selector for operator pod
nodeSelector: {}

# Pod security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Monitoring - FIXED label references
podLabels:
  monitoring: "true"
  app: spark-operator
  prometheus: kube-prometheus

# Log level
logLevel: info

# Leader election (for HA)
leaderElection:
  lockName: spark-operator-lock
  lockNamespace: spark

# Ingress class to add to Spark UI services
ingressUrlFormat: ""

# Environment variables for the operator
env: []

# Volume mounts for the operator
volumeMounts: []

# Volumes for the operator
volumes: []

# Affinity settings for the operator
affinity: {}

# Tolerations for the operator
tolerations: []

# Priority class for the operator
priorityClassName: ""

# Pod annotations
podAnnotations: {}

# Install CRDs
installCRDs: true

# Time to live for Spark UI service
uiService:
  enable: true