apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-stack-grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2  # Using gp2 as we confirmed it exists