apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - create-webhook-cert
  - ingress.yaml
  - prometheus-rbac.yaml
  - servicemonitors/spark-servicemonitor.yaml 
  - servicemonitors/dremio-servicemonitor.yaml 
  - servicemonitors/airflow-servicemonitor.yaml 

commonLabels:
  app.kubernetes.io/part-of: data-platform
  app.kubernetes.io/managed-by: argocd