kubectl apply -f applications/monitoring-helm.yaml
kubectl apply -f applications/monitoring-resources.yaml
kubectl apply -f applications/postgresql-helm.yaml
kubectl apply -f applications/postgresql-resources.yaml
kubectl apply -f applications/spark-helm.yaml
kubectl apply -f applications/spark-resources.yaml
kubectl apply -f applications/minio.yaml
kubectl apply -f applications/airflow-helm.yaml
kubectl apply -f applications/airflow-resources.yaml
kubectl apply -f applications/dremio-helm.yaml
kubectl apply -f applications/dremio-resources.yaml
