# Secrets for airflow-helm chart
---
# Database password secret (format expected by airflow-helm chart)
apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata-secret
  namespace: airflow
type: Opaque
stringData:
  # The airflow-helm chart expects the key to be "password"
  password: "airflow123"
  # Also keep the connection string for backward compatibility
  connection: "postgresql+psycopg2://airflow:airflow123@postgresql.postgresql.svc.cluster.local:5432/airflow"
---
# Fernet key secret
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow
type: Opaque
stringData:
  fernet-key: "fk6Rc2F9PvDkGPKpbGq6ysKmluXCHzpMwJitx-JB8JU="
---
# Webserver secret key
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret-key
  namespace: airflow
type: Opaque
stringData:
  webserver-secret-key: "a8f6e4c2d1b3e5f7a9c0d2e4f6a8b0c2"