# Airflow secrets - Using external PostgreSQL
---
# Secret for Airflow metadata database connection
apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata-secret
  namespace: airflow
type: Opaque
stringData:
  # Connection to PostgreSQL in postgresql namespace
  # Format: postgresql+psycopg2://username:password@host:port/database
  connection: postgresql+psycopg2://airflow:airflow123@postgresql.postgresql.svc.cluster.local:5432/airflow
---
# Secret for Airflow result backend (for CeleryExecutor - not used with KubernetesExecutor)
apiVersion: v1
kind: Secret
metadata:
  name: airflow-result-backend-secret
  namespace: airflow
type: Opaque
stringData:
  # db+ prefix for Celery result backend
  connection: db+postgresql://airflow:airflow123@postgresql.postgresql.svc.cluster.local:5432/airflow
---
# Fernet key for encryption - MUST BE CHANGED IN PRODUCTION!
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow
type: Opaque
stringData:
  fernet-key: "fk6Rc2F9PvDkGPKpbGq6ysKmluXCHzpMwJitx-JB8JU="
---
# Webserver secret key - MUST BE CHANGED IN PRODUCTION!
# Generate with: python -c "import secrets; print(secrets.token_hex(16))"
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret
  namespace: airflow
type: Opaque
stringData:
  # Environment variable format for webserver secret key
  AIRFLOW__WEBSERVER__SECRET_KEY: "a8f6e4c2d1b3e5f7a9c0d2e4f6a8b0c2"