# Airflow secrets - Using external PostgreSQL
---
# Secret for Airflow metadata database connection
apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata-secret
  namespace: airflow
type: Opaque
stringData:
  # Connection to PostgreSQL in postgresql namespace
  connection: postgresql+psycopg2://airflow:airflow123@postgresql.postgresql.svc.cluster.local:5432/airflow
---
# Secret for Airflow result backend
apiVersion: v1
kind: Secret
metadata:
  name: airflow-result-backend-secret
  namespace: airflow
type: Opaque
stringData:
  connection: db+postgresql://airflow:airflow123@postgresql.postgresql.svc.cluster.local:5432/airflow
---
# Fernet key for encryption
apiVersion: v1
kind: Secret
metadata:
  name: airflow-fernet-key
  namespace: airflow
type: Opaque
stringData:
  fernet-key: "fk6Rc2F9PvDkGPKpbGq6ysKmluXCHzpMwJitx-JB8JU="
---
# Webserver secret key - NOTE: Chart expects specific name and key
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret-key  # Changed to match what chart expects
  namespace: airflow
type: Opaque
stringData:
  webserver-secret-key: "a8f6e4c2d1b3e5f7a9c0d2e4f6a8b0c2"
---
# Also keep the original for backward compatibility
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret
  namespace: airflow
type: Opaque
stringData:
  AIRFLOW__WEBSERVER__SECRET_KEY: "a8f6e4c2d1b3e5f7a9c0d2e4f6a8b0c2"