apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

resources:
  - namespace.yaml
  - airflow-secrets.yaml  # Database connection secrets
  - dags-pvc.yaml        # DAGs storage
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: data-platform
  app.kubernetes.io/managed-by: argocd