apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airflow

resources:
  - namespace.yaml
  - airflow-secrets.yaml           # Database connection secrets
  - dags-pvc.yaml                  # DAGs storage
  - ingress.yaml
  - airflow-servicemonitor.yaml    # Prometheus service monitors
  - airflow-prometheus-rules.yaml  # Alert rules
  - statsd-mapping-config.yaml     # StatsD to Prometheus mapping

commonLabels:
  app.kubernetes.io/part-of: data-platform
  app.kubernetes.io/managed-by: argocd