apiVersion: v1
kind: ServiceAccount
metadata:
  name: dremio-cluster-id
  namespace: dremio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dremio-cluster-id
  namespace: dremio
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "patch", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dremio-cluster-id
  namespace: dremio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dremio-cluster-id
subjects:
- kind: ServiceAccount
  name: dremio-cluster-id
  namespace: dremio
- kind: ServiceAccount
  name: default
  namespace: dremio