apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: data-platform
  sources:
    # Helm chart source
    - repoURL: https://airflow-helm.github.io/charts
      chart: airflow
      targetRevision: 8.9.0  # Latest stable version of airflow-helm chart
      helm:
        releaseName: airflow
        valueFiles:
          - $values/values/airflow-values.yaml
    # Git repo with values
    - repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m