apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio-enterprise
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: quay.io
    chart: dremio/dremio-helm
    targetRevision: 3.0.1  # Specify the version you want, or use latest
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/ibrahimself/data-platform-k8s-configs/HEAD/values/dremio-values.yaml
      # Optional: Override specific values
      parameters:
      - name: image
        value: quay.io/dremio/dremio-ee
      - name: imageTag
        value: "26.0.1"  # Use your desired version
      - name: imagePullSecrets[0]
        value: dremio-quay-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: dremio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: ""
    kind: ConfigMap
    name: dremio-cluster-id
    jsonPointers:
    - /data/cluster_id