apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  sources:
    # Source 1: Git repo for values and secrets
    - repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
      targetRevision: HEAD
      ref: values
    # Source 2: Dremio Helm chart from OCI registry
    - repoURL: registry-1.docker.io
      chart: dremio/dremio-enterprise
      targetRevision: 3.0.2
      helm:
        releaseName: dremio
        valueFiles:
          - $values/values/dremio-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dremio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
  info:
    - name: 'sync-wave'
      value: '15'