apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio-enterprise
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:  # Note: "source" not "sources"
    repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
    targetRevision: HEAD
    path: charts/dremio-helm  # Path to the chart in your Git repo
    helm:
      releaseName: dremio-enterprise
      valueFiles:
        - ../../values/dremio-values.yaml  # Path relative to the chart
  destination:
    server: https://kubernetes.default.svc
    namespace: dremio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground