apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
    targetRevision: HEAD
    path: resources/dremio
    helm:
      valueFiles:
        - values-overrides.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dremio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true