apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
    path: resources/dremio-chart
    targetRevision: HEAD  # or specific branch/tag
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dremio
  syncPolicy:
    automated:
      prune: true
      selfHeal: false  # Disable self-heal
  ignoreDifferences:
  - group: apps
    kind: Deployment
    name: dremio-mongodb-operator
  - group: apps
    kind: Deployment
    name: dremio-catalog-server
  - group: apps
    kind: Deployment
    name: dremio-catalog-services-server
  - group: apps
    kind: Deployment  
    name: engine-operator