apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio-enterprise
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  sources:
    # Source 1: Git repo for values
    - repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
      targetRevision: HEAD
      ref: values
    # Source 2: Dremio Helm chart from OCI
    - repoURL: quay.io
      chart: dremio/dremio-helm
      targetRevision: "3.0.1"
      helm:
        releaseName: dremio-enterprise
        valueFiles:
          - $values/values/dremio-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dremio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m