apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio-enterprise
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
    targetRevision: HEAD
    path: charts/dremio-helm
    helm:
      releaseName: dremio-enterprise
      valueFiles:
        - ../../values/dremio-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dremio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - Replace=true  # Add this to replace existing resources
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m