# Option 1: Update ArgoCD Application to Respect Existing PVCs
# applications/monitoring-helm.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  sources:
    - repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 56.6.2
      helm:
        releaseName: prometheus-stack
        valueFiles:
          - $values/values/monitoring-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      # REMOVE Replace=true for PVCs
      - RespectIgnoreDifferences=true  # ADD THIS
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # ADD: Ignore PVC differences
  ignoreDifferences:
    # Ignore PVC spec changes
    - group: ""
      kind: PersistentVolumeClaim
      name: prometheus-stack-grafana
      jsonPointers:
        - /spec
    - group: ""
      kind: PersistentVolumeClaim
      name: prometheus-prometheus-stack-kube-prom-prometheus-db-prometheus-prometheus-stack-kube-prom-prometheus-0
      jsonPointers:
        - /spec
    - group: ""
      kind: PersistentVolumeClaim
      name: alertmanager-prometheus-stack-kube-prom-alertmanager-db-alertmanager-prometheus-stack-kube-prom-alertmanager-0
      jsonPointers:
        - /spec
    # Also ignore webhook resources
    - group: batch
      kind: Job
      name: prometheus-stack-kube-prom-admission-create
    - group: batch
      kind: Job
      name: prometheus-stack-kube-prom-admission-patch