apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  sources:
    # Source 1: Git repo for values file
    - repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
      targetRevision: HEAD
      ref: values
    # Source 2: Helm chart
    - repoURL: https://kubeflow.github.io/spark-operator
      chart: spark-operator
      targetRevision: 1.1.27
      helm:
        releaseName: spark-operator
        skipCrds: false
        valueFiles:
          - $values/values/spark-values.yaml  # Use your values file!
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/annotations/argocd.argoproj.io~1hook
        - /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  revisionHistoryLimit: 3
  info:
    - name: 'sync-wave'
      value: '20'