apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  sources:
    # Source 1: Git repo for values file
    - repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://kubeflow.github.io/spark-operator
      chart: spark-operator
      targetRevision: 1.1.27
      helm:
        releaseName: spark-operator
        values: |
          # CRITICAL: Use numeric log level
          logLevel: 2
          
          # CRITICAL: Use correct image
          image:
            repository: gcr.io/spark-operator/spark-operator
            tag: v1beta2-1.3.8-3.1.1
            pullPolicy: IfNotPresent
          
          webhook:
            enable: false
          
          sparkJobNamespace: spark
          
          serviceAccounts:
            spark:
              create: true
              name: spark
            sparkoperator:
              create: true
              name: spark-operator
          
          rbac:
            create: true
            createRole: true
            createClusterRole: true
          
          controllerThreads: 10
          resyncInterval: 30
          
          batchScheduler:
            enable: false
          
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 300Mi
          
          metrics:
            enable: true
            port: 10254
            endpoint: /metrics
          
          uiService:
            enable: true
          
          resourceQuotaEnforcement:
            enable: false
          
          # Node affinity to avoid overloaded nodes
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - ip-10-0-2-152.eu-west-3.compute.internal
                    - ip-10-0-2-5.eu-west-3.compute.internal
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - SkipHooks=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m