apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  sources:
    # Source 1: Git repo for values file
    - repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
      targetRevision: HEAD
      ref: values
    # Source 2: Helm chart
    - repoURL: https://kubeflow.github.io/spark-operator
      chart: spark-operator
      targetRevision: 1.1.27
      helm:
        releaseName: spark-operator
        values: |
          # Match exactly what worked in Helm
          webhook:
            enable: false
          sparkJobNamespace: spark
          serviceAccounts:
            spark:
              create: true
              name: spark
            sparkoperator:
              create: true
              name: spark-operator
          rbac:
            create: true
            createRole: true
            createClusterRole: true
          controllerThreads: 10
          resyncInterval: 30
          batchScheduler:
            enable: false
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 300Mi
          metrics:
            enable: true
            port: 10254
            endpoint: /metrics
          uiService:
            enable: true
          resourceQuotaEnforcement:
            enable: false
          logLevel: info
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true  # Only apply changes
      - SkipHooks=true           # Skip hooks
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/annotations
        - /metadata/labels
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
      name: spark-operator
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
      name: spark-operator