apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://kubeflow.github.io/spark-operator
    chart: spark-operator
    targetRevision: 1.1.27  # Keep the version you originally specified
    helm:
      releaseName: spark-operator
      values: |
        # CRITICAL: Use the correct image repository and tag
        image:
          repository: gcr.io/spark-operator/spark-operator
          tag: v1beta2-1.3.8-3.1.1  # This is a known working tag
          pullPolicy: IfNotPresent
        
        # Webhook configuration
        webhook:
          enable: false  # Disable initially to simplify deployment
          port: 443
        
        # Service account configuration
        serviceAccounts:
          spark:
            create: true
            name: spark
          sparkoperator:
            create: true
            name: spark-operator
        
        # RBAC configuration
        rbac:
          create: true
          createClusterRole: true
          createRole: true
        
        # Controller configuration
        controllerThreads: 10
        resyncInterval: 30
        
        # Resources
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
        
        # Metrics
        metrics:
          enable: true
          port: 10254
          endpoint: /metrics
          prefix: ""
        
        # Prometheus monitoring
        prometheus:
          metrics:
            enable: true
            port: 10254
            endpoint: /metrics
          serviceMonitor:
            enable: true
            labels:
              prometheus: kube-prometheus-stack
            interval: 30s
        
        # Log level
        logLevel: info
        
        # Leader election
        leaderElection:
          enable: true
          lockName: spark-operator-lock
          lockNamespace: spark
        
        # Spark job namespace
        sparkJobNamespace: spark
        
        # Pod security context
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
        
        # Enable CRD creation
        createCRD: true
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
    - name: 'sync-wave'
      value: '20'