apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://kubeflow.github.io/spark-operator
    chart: spark-operator
    targetRevision: 1.1.27
    helm:
      releaseName: spark-operator
      # Skip hooks to avoid PreSync issues with RBAC
      skipHooks: true
      values: |
        # Use correct image
        image:
          repository: gcr.io/spark-operator/spark-operator
          tag: v1beta2-1.3.8-3.1.1
          pullPolicy: IfNotPresent
        
        # Basic configuration
        sparkJobNamespace: spark
        
        webhook:
          enable: false
        
        serviceAccounts:
          spark:
            create: true
          sparkoperator:
            create: true
        
        rbac:
          create: true
        
        # Enable metrics for Prometheus
        metrics:
          enable: true
          port: 10254
          endpoint: /metrics
          prefix: ""
        
        # Prometheus monitoring configuration
        prometheus:
          metrics:
            enable: true
            port: 10254
            endpoint: /metrics
          serviceMonitor:
            enable: true
            labels:
              prometheus: kube-prometheus-stack
              release: prometheus
            interval: 30s
            scrapeTimeout: 10s
        
        # Controller threads for performance
        controllerThreads: 10
        
        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 500Mi
        
        # Log level
        logLevel: info
        
        # Pod labels for better monitoring
        podLabels:
          monitoring: "true"
          app.kubernetes.io/component: "spark-operator"
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true  # This will replace existing resources
      - ApplyOutOfSyncOnly=true  # Only apply resources that are out of sync
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Ignore differences in RBAC resources to handle existing ones
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: spark-operator
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: spark-operator
  info:
    - name: 'sync-wave'
      value: '