apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://kubeflow.github.io/spark-operator
    chart: spark-operator
    targetRevision: 1.1.27
    helm:
      releaseName: spark-operator
      values: |
        # Use correct image
        image:
          repository: gcr.io/spark-operator/spark-operator
          tag: v1beta2-1.3.8-3.1.1
          pullPolicy: IfNotPresent
        
        # Basic configuration only
        sparkJobNamespace: spark
        
        webhook:
          enable: false
        
        serviceAccounts:
          spark:
            create: true
          sparkoperator:
            create: true
        
        rbac:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  info:
    - name: 'sync-wave'
      value: '20'