apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: git@github.com:ibrahimself/data-platform-k8s-configs.git
    targetRevision: HEAD
    path: resources/spark
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Sync wave to create namespace and resources first
  info:
    - name: 'sync-wave'
      value: '19'