apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  source:
    repoURL: https://kubeflow.github.io/spark-operator
    chart: spark-operator
    targetRevision: 1.1.27
    helm:
      releaseName: spark-operator
      values: |
        # Use correct image
        image:
          repository: gcr.io/spark-operator/spark-operator
          tag: v1beta2-1.3.8-3.1.1
          pullPolicy: IfNotPresent
        
        # Basic configuration
        sparkJobNamespace: spark
        
        webhook:
          enable: false
        
        serviceAccounts:
          spark:
            create: true
          sparkoperator:
            create: true
        
        rbac:
          create: true
        
        # Enable metrics for Prometheus
        metrics:
          enable: true
          port: 10254
          endpoint: /metrics
          prefix: ""
        
        # Prometheus monitoring configuration
        prometheus:
          metrics:
            enable: true
            port: 10254
            endpoint: /metrics
          serviceMonitor:
            enable: true
            # Labels must match your Prometheus ServiceMonitor selector
            labels:
              prometheus: kube-prometheus-stack
              release: prometheus  # Adjust based on your Prometheus installation
            interval: 30s
            scrapeTimeout: 10s
            # Additional labels for the ServiceMonitor
            additionalLabels: {}
            # Metric relabeling configurations
            metricRelabelings: []
            # Relabeling configurations
            relabelings: []
        
        # Controller threads for performance
        controllerThreads: 10
        
        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 500Mi
        
        # Log level
        logLevel: info
        
        # Pod labels for better monitoring
        podLabels:
          monitoring: "true"
          app.kubernetes.io/component: "spark-operator"
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  info:
    - name: 'sync-wave'
      value