apiVersion: v2
dependencies:
- alias: mongodbOperator
  name: dremio-mongodb-operator-helm
  repository: oci://quay.io/dremio
  version: 1.19.1-dremio-20250319174037-b8594c2
- condition: nats.enabled
  name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: 1.3.1
- alias: opensearchOperator
  condition: opensearch.enabled
  name: dremio-opensearch-operator-helm
  repository: oci://quay.io/dremio
  version: 2.7.0-dremio-20250401092400-0f5e57b
home: https://www.dremio.com/
keywords:
- dremio
- data
name: dremio-helm
type: application
version: 3.0.1
