#
# Copyright (C) 2017-2019 Dremio Corporation. This file is confidential and private property.
#

{{- if  $.Values.dremio.trialImagePullCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: dremio-trial-image-pull-credentials
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-10"
data:
  .dockerconfigjson: {{ $.Values.dremio.trialImagePullCredentials | quote }}
type: kubernetes.io/dockerconfigjson
{{- end -}}
