apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spark

resources:
  - namespace.yaml
  - spark-history-server.yaml
  - spark-operator-servicemonitor.yaml
  - ingress.yaml

# Create ConfigMap for Spark defaults
configMapGenerator:
  - name: spark-defaults
    files:
      - spark-defaults.conf

# Common labels
commonLabels:
  app.kubernetes.io/part-of: data-platform
  app.kubernetes.io/managed-by: argocd