apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spark

resources:
  - namespace.yaml
  - spark-history-server.yaml
  - ingress.yaml
  - spark-operator-servicemonitor.yaml 
  - spark-operator-metrics-service.yaml

configMapGenerator:
  - name: spark-defaults
    files:
      - spark-defaults.conf

commonLabels:
  app.kubernetes.io/part-of: data-platform
  app.kubernetes.io/managed-by: argocd