apiVersion: v1
kind: Service
metadata:
  name: spark-operator-metrics
  namespace: spark
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/component: metrics
spec:
  selector:
    app.kubernetes.io/name: spark-operator
  ports:
  - name: metrics
    port: 10254
    targetPort: 10254
    protocol: TCP
  type: ClusterIP