apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-operator
  namespace: spark
  labels:
    app: spark-operator
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-operator
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s