apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-operator-metrics
  namespace: spark
  labels:
    app: spark-operator
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-operator
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
---
# ServiceMonitor for Spark Applications
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-applications
  namespace: spark
  labels:
    app: spark-applications
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      sparkoperator.k8s.io/launched-by-spark-operator: "true"
  endpoints:
  - port: prometheus
    path: /metrics/prometheus
    interval: 30s
  namespaceSelector:
    matchNames:
    - spark