{
 "title": "Spark Operator Metrics",
 "tags": [
  "spark",
  "data-platform"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Spark Applications Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "spark_app_count" }
   ]
  },
  {
   "title": "Total Spark App Submissions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(spark_app_submit_count)" }
   ]
  },
  {
   "title": "Spark Application Status Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "spark_app_running_count", "legendFormat": "Running" },
    { "expr": "spark_app_success_count", "legendFormat": "Success" },
    { "expr": "spark_app_failure_count", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Spark Application Start Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(spark_app_start_latency_microseconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(spark_app_start_latency_microseconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}