#
# Copyright (C) 2017-2019 Dremio Corporation. This file is confidential and private property.
#

{{- if $.Values.catalogservices.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dremio.catalogservices.app.name" $ }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "dremio.catalogservices.app.name" $ }}
  ports:
    - name: catalog-grpc
      port: {{ include "dremio.catalogservices.ports.grpc" $ }}
      targetPort: {{ include "dremio.catalogservices.ports.grpc" $ }}
      protocol: TCP
{{- end -}}
