#
# Copyright (C) 2017-2019 Dremio Corporation. This file is confidential and private property.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mongodb.serviceAccount }}
  namespace: {{ .Release.Namespace }}
{{- include "dremio.imagePullSecrets" $ }}
---
{{- if not ( lookup "v1" "Secret" .Release.Namespace ( include "dremio.mongodb.userSecret" . ) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dremio.mongodb.userSecret" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{ include "dremio.mongodb.user" . }}: "{{ randAlphaNum 32 }}"
{{- end }}
---
apiVersion: psmdb.dremio.com/v1
kind: PerconaServerMongoDB
metadata:
  name: {{ include "dremio.mongodb.cluster" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: dremio
    app.kubernetes.io/instance: {{ .Release.Name }}
    app-group: dremio
    {{- if .Values.mongodb.labels }}
    {{- tpl (toYaml .Values.mongodb.labels) . | nindent 4 }}
    {{- end }}
  {{- include "dremio.mongodb.annotations" $ | nindent 2 }}
spec:
  crVersion: 1.19.1
  image: {{ $.Values.mongodb.image.repository }}:{{ $.Values.mongodb.image.tag }}
  imagePullPolicy: {{ $.Values.mongodb.image.pullPolicy }}
  {{ if .Values.devMode -}}
  unsafeFlags:
    replsetSize: true
  {{ end -}}
  updateStrategy: SmartUpdate
  upgradeOptions:
    # No automatic upgrades
    apply: Disabled # Recommended, Latest, Disabled
  secrets:
    users: {{ include "dremio.mongodb.cluster" . }}-system-users
  users:
    - name: {{ include "dremio.mongodb.user" . }}
      db: {{ include "dremio.mongodb.db" . }}
      passwordSecretRef:
        name: {{ include "dremio.mongodb.userSecret" . }}
        key: {{ include "dremio.mongodb.user" . }}
      roles:
        - name: readWrite
          db: {{ include "dremio.mongodb.db" . }}
  enableVolumeExpansion: {{ .Values.mongodb.enableVolumeExpansion }}
  replsets:
    - name: rs0
      size: {{ .Values.mongodb.replicaCount }}
      serviceAccountName: {{ .Values.mongodb.serviceAccount }}
      resources:
        {{- tpl (toYaml .Values.mongodb.resources) . | nindent 8 }}
      {{- include "dremio.mongodb.podLabels" $ | nindent 6 }}
      annotations:
        metrics.dremio.com/scrape: "true"
        metrics.dremio.com/port: {{ include "dremio.mongodb.ports.metrics.internal" . | quote }}
        metrics.dremio.com/path: "/metrics"
        {{- include "dremio.mongodb.podAnnotations" $ | nindent 8 }}
      {{- include "dremio.mongodb.nodeSelector" $ | nindent 6 }}
      {{- include "dremio.mongodb.tolerations" $ | nindent 6 }}
      {{- if .Values.mongodb.affinity }}
      affinity:
        {{- tpl (toYaml .Values.mongodb.affinity) . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range . }}
        - {{ tpl (toYaml .) . | indent 10 | trim }}
      {{- end }}
      {{- end }}
      {{- if .Values.mongodb.priorityClassName }}
      priorityClassName: {{ .Values.mongodb.priorityClassName }}
      {{- end }}
      {{- if .Values.mongodb.podDisruptionBudget }}
      podDisruptionBudget:
        {{- tpl (toYaml .Values.mongodb.podDisruptionBudget) . | nindent 8 }}
      {{- end }}
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 0
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      volumeSpec:
        persistentVolumeClaim:
          {{- tpl (toYaml .Values.mongodb.storage) . | nindent 10 }}
