#
# Copyright (C) 2017-2019 Dremio Corporation. This file is confidential and private property.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.opensearch.serviceAccount }}
{{- include "dremio.imagePullSecrets" $ }}
