# Dremio Enterprise Values - Following Official Structure
# Based on Dremio 26.x documentation

# License Configuration (Required)
dremio:
  license: "eyJraWQiOiI4MGZhMjgxYzZhZjczNDNkNTE1YTVhMzg1MDg1N2RhNmE2YmEzMTU3NWE5ZjVlZmVhMmQ4MTkyMGUyM2Q2OGY0IiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJEcmVtaW8iLCJzdWIiOiIwMDM1ZDAwMDA3TFRkT0VBQTEiLCJuYmYiOjE3NTI3ODA0NzYsImV4cCI6MTc1NTU0NTI3NiwiaWF0IjoxNzUyNzgwNDc2LCJqdGkiOiIxNzUyNzgwNDc2MDYyVzJjciJ9.u8bxfpQvyieeGn3H8RNIyKqbIgHR4pYO0mfBDBh23WJJw58t2WsDEhbOL6rUdfyGu4hItUtcohCoSEXMaAAolg"
  
  # Enterprise Edition image
  image:
    repository: quay.io/dremio/dremio-enterprise

# Image Pull Secrets
imagePullSecrets:
  - dremio-pull-secret

# Coordinator Configuration
coordinator:
  # Production resources
  resources:
    requests:
      cpu: 32
      memory: 64Gi
    limits:
      memory: 64Gi
  
  # Storage
  volumeSize: 512Gi
  
  # Scale-out coordinators (0 = only primary)
  count: 0
  
  # Web UI Configuration
  web:
    auth:
      enabled: true
      type: "internal"  # Change to azuread, ldap, oauth as needed
    tls:
      enabled: false
  
  # Client Configuration
  client:
    tls:
      enabled: false
  
  # Flight Configuration  
  flight:
    tls:
      enabled: false

# Distributed Storage Configuration (REQUIRED)
# Choose one of: aws, azureStorage, or gcp
distStorage:
  type: "aws"  # Change based on your cloud provider
  
  # AWS S3 Configuration
  aws:
    bucketName: "your-dremio-bucket"  # CHANGE THIS
    path: "/dremio"
    authentication: "instanceMetadata"  # or "accessKeySecret"
    # If using accessKeySecret, uncomment below
    # credentials:
    #   accessKey: "your-access-key"
    #   secret: "your-secret"
  
  # # Azure Storage Configuration
  # type: "azureStorage"
  # azureStorage:
  #   accountName: "your-storage-account"
  #   authentication: "accessKey"
  #   filesystem: "dremio-container"
  #   path: "/"
  #   credentials:
  #     accessKey: "your-storage-key"
  
  # # GCS Configuration
  # type: "gcp"
  # gcp:
  #   bucketName: "your-gcs-bucket"
  #   path: "/"
  #   authentication: "auto"

# Enterprise Catalog Configuration (REQUIRED)
catalog:
  externalAccess:
    enabled: true
  
  storage:
    # Must match your distStorage type
    type: "S3"  # or "AZURE" or "GCS"
    location: "s3://your-catalog-bucket/catalog"  # CHANGE THIS
    
    # S3 Catalog Configuration
    s3:
      region: "us-east-1"  # CHANGE THIS
      roleArn: "arn:aws:iam::123456789:role/dremio-catalog-role"  # CHANGE THIS
      userArn: "arn:aws:iam::123456789:user/dremio-catalog-user"  # CHANGE THIS
      externalId: "dremio-catalog-external-id"  # CHANGE THIS
      useAccessKeys: false
    
    # # Azure Catalog Configuration
    # type: "AZURE"
    # location: "abfss://container@storageaccount.dfs.core.windows.net/catalog"
    # azure:
    #   authentication: "accessKey"
    #   accountName: "your-storage-account"
    #   accountKind: "StorageV2"
    
    # # GCS Catalog Configuration
    # type: "GCS"
    # location: "gs://your-bucket/catalog"
    # gcs:
    #   projectId: "your-project-id"
    #   authentication: "auto"

# Service Configuration
service:
  type: LoadBalancer  # or ClusterIP if using Ingress
  sessionAffinity: true  # Important for scale-out coordinators
  # For AWS EKS in Auto Mode
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

# Ingress Configuration (Optional)
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: dremio.yourdomain.com  # CHANGE THIS
      paths:
        - /
  tls:
    - secretName: dremio-tls
      hosts:
        - dremio.yourdomain.com

# Production Resources Configuration
opensearch:
  enabled: true
  resources:
    requests:
      memory: 16Gi
      cpu: 2
  volumeSize: 100Gi
  replicas: 3

mongodb:
  resources:
    requests:
      memory: 4Gi
      cpu: 8
  volumeSize: 512Gi
  replicas: 3

zookeeper:
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
  volumeSize: 10Gi
  count: 3

nats:
  resources:
    requests:
      memory: 1Gi
      cpu: 700m

catalog:
  resources:
    requests:
      memory: 8Gi
      cpu: 4

catalogExternalAccessServer:
  resources:
    requests:
      memory: 8Gi
      cpu: 4

catalogServiceServer:
  resources:
    requests:
      memory: 8Gi
      cpu: 4

engineOperator:
  resources:
    requests:
      memory: 1Gi
      cpu: 1

# Engine Configuration (New Engines)
engine:
  options:
    resourceAllocationOffsets:
      defaultOffset: reserve-2-8

# Telemetry
telemetry:
  enabled: true

# Global metadata (optional)
labels: {}
annotations: {}
tolerations: []
nodeSelector: {}