# argocd-apps/spark/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spark

resources:
  - namespace.yaml
  - spark-history-pvc.yaml  # PVC for history server logs
  - ingress.yaml

# Deploy Spark Operator via Helm
helmCharts:
  - name: spark-operator
    repo: https://kubeflow.github.io/spark-operator
    version: 1.1.27  # Latest version for Spark 3.5.x support
    releaseName: spark-operator
    namespace: spark
    valuesFile: values.yaml

# Deploy additional Spark components
configMapGenerator:
  - name: spark-history-config
    files:
      - spark-defaults.conf

# Common labels
commonLabels:
  app.kubernetes.io/part-of: data-platform
  app.kubernetes.io/managed-by: