# argocd/applications.yaml
# ArgoCD Application definitions for GitOps deployment

---
# ArgoCD Project for Data Platform
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data-platform
  namespace: argocd
spec:
  description: Data Platform Applications
  
  # Source repositories
  sourceRepos:
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://kubeflow.github.io/spark-operator'
    - 'https://helm.dremio.com'
    - 'https://airflow.apache.org'
    - 'https://git-codecommit.eu-west-3.amazonaws.com/v1/repos/data-platform-k8s-configs'
    - '*'
  
  # Destination clusters and namespaces
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  
  # RBAC policies
  roles:
    - name: admin
      description: Admin access to data platform applications
      policies:
        - p, proj:data-platform:admin, applications, *, data-platform/*, allow
        - p, proj:data-platform:admin, repositories, *, *, allow
      groups:
        - data-platform-admins
    
    - name: developer
      description: Developer access to data platform applications
      policies:
        - p, proj:data-platform:developer, applications, get, data-platform/*, allow
        - p, proj:data-platform:developer, applications, sync, data-platform/*, allow
      groups:
        - data-platform-developers

  # Cluster resource whitelist
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration

  # Namespace resource whitelist
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

---
# Git Repository Secret for CodeCommit
apiVersion: v1
kind: Secret
metadata:
  name: codecommit-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://git-codecommit.eu-west-3.amazonaws.com/v1/repos/data-platform-k8s-configs
  # Update with your CodeCommit credentials
  username: <CODECOMMIT_USERNAME>
  password: <CODECOMMIT_PASSWORD>

---
# Monitoring Stack Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: monitoring-stack
    app.kubernetes.io/part-of: data-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "45.7.1"
    helm:
      valueFiles:
      - $values/monitoring/values.yaml
  - repoURL: https://git-codecommit.eu-west-3.amazonaws.com/v1/repos/data-platform-k8s-configs
    targetRevision: HEAD
    ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  
  revisionHistoryLimit: 3

---
# Spark Operator Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/part-of: data-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  
  sources:
  - repoURL: https://kubeflow.github.io/spark-operator
    chart: spark-operator
    targetRevision: "1.1.27"
    helm:
      valueFiles:
      - $values/spark/values.yaml
  - repoURL: https://git-codecommit.eu-west-3.amazonaws.com/v1/repos/data-platform-k8s-configs
    targetRevision: HEAD
    ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: spark
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  
  revisionHistoryLimit: 3

---
# Dremio Enterprise Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio-enterprise
  namespace: argocd
  labels:
    app.kubernetes.io/name: dremio-enterprise
    app.kubernetes.io/part-of: data-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  
  sources:
  - repoURL: https://helm.dremio.com
    chart: dremio-enterprise
    targetRevision: "26.0"
    helm:
      valueFiles:
      - $values/dremio/values.yaml
  - repoURL: https://git-codecommit.eu-west-3.amazonaws.com/v1/repos/data-platform-k8s-configs
    targetRevision: HEAD
    ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dremio
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  
  revisionHistoryLimit: 3

---
# Apache Airflow Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-airflow
  namespace: argocd
  labels:
    app.kubernetes.io/name: apache-airflow
    app.kubernetes.io/part-of: data-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-platform
  
  sources:
  - repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: "1.7.0"
    helm:
      valueFiles:
      - $values/airflow/values.yaml
  - repoURL: https://git-codecommit.eu-west-3.amazonaws.com/v1/repos/data-platform-k8s-configs
    targetRevision: HEAD
    ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  
  revisionHistoryLimit: 3