# Dremio Deployment with reduced resource requirements for small clusters
---
# ConfigMap for Dremio configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: dremio-config
  namespace: dremio
data:
  dremio.conf: |
    paths: {
      local: "/opt/dremio/data"
      dist: "pdfs:///opt/dremio/data/dist"
    }
    
    services: {
      coordinator: {
        enabled: true
        master: {
          enabled: true
          embedded-zookeeper: {
            enabled: true
            port: 2181
          }
        }
        web: {
          enabled: true
          port: 9047
          ssl.enabled: false
        }
      }
      executor: {
        enabled: false
      }
    }
  dremio-env: |
    DREMIO_MAX_HEAP_MEMORY_SIZE_MB=2048
    DREMIO_MAX_DIRECT_MEMORY_SIZE_MB=2048
---
# Single Dremio instance (coordinator + executor combined)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio
  namespace: dremio
spec:
  serviceName: dremio-cluster
  replicas: 1
  selector:
    matchLabels:
      app: dremio
  template:
    metadata:
      labels:
        app: dremio
    spec:
      serviceAccountName: dremio
      imagePullSecrets:
        - name: dremio-pull-secret
        - name: dremio-trial-pull-secret
      containers:
      - name: dremio
        image: quay.io/dremio/dremio-enterprise:26.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: DREMIO_JAVA_SERVER_EXTRA_OPTS
          value: >-
            -Dpaths.local=/opt/dremio/data
            -Dservices.coordinator.enabled=true
            -Dservices.executor.enabled=true
            -Dservices.coordinator.master.enabled=true
            -Dservices.coordinator.web.port=9047
            -Xmx2g
            -XX:MaxDirectMemorySize=2g
        - name: DREMIO_LICENSE
          value: "eyJraWQiOiI4MGZhMjgxYzZhZjczNDNkNTE1YTVhMzg1MDg1N2RhNmE2YmEzMTU3NWE5ZjVlZmVhMmQ4MTkyMGUyM2Q2OGY0IiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJEcmVtaW8iLCJzdWIiOiIwMDM1ZDAwMDA3TFRkT0VBQTEiLCJuYmYiOjE3NTI3ODA0NzYsImV4cCI6MTc1NTU0NTI3NiwiaWF0IjoxNzUyNzgwNDc2LCJqdGkiOiIxNzUyNzgwNDc2MDYyVzJjciJ9.u8bxfpQvyieeGn3H8RNIyKqbIgHR4pYO0mfBDBh23WJJw58t2WsDEhbOL6rUdfyGu4hItUtcohCoSEXMaAAolg"
        ports:
        - containerPort: 9047
          name: web
        - containerPort: 31010
          name: client
        - containerPort: 45678
          name: server
        - containerPort: 32010
          name: flight
        resources:
          requests:
            cpu: 500m
            memory: 3Gi
          limits:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - name: dremio-config
          mountPath: /opt/dremio/conf
        - name: dremio-data
          mountPath: /opt/dremio/data
        livenessProbe:
          httpGet:
            path: /
            port: 9047
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 9047
          initialDelaySeconds: 120
          periodSeconds: 10
      volumes:
      - name: dremio-config
        configMap:
          name: dremio-config
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
  volumeClaimTemplates:
  - metadata:
      name: dremio-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 50Gi
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: dremio-cluster
  namespace: dremio
spec:
  type: ClusterIP
  selector:
    app: dremio
  ports:
  - name: web
    port: 9047
    targetPort: 9047
  - name: client
    port: 31010
    targetPort: 31010
  - name: flight
    port: 32010
    targetPort: 32010
---
# Service for web UI
apiVersion: v1
kind: Service
metadata:
  name: dremio-client
  namespace: dremio
spec:
  type: ClusterIP
  selector:
    app: dremio
  ports:
  - name: web
    port: 9047
    targetPort: 9047
  - name: flight
    port: 32010
    targetPort: 32010
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dremio
  namespace: dremio