# Dremio OSS Deployment (no authentication required)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dremio-config
  namespace: dremio
data:
  dremio.conf: |
    paths: {
      local: "/opt/dremio/data"
      dist: "pdfs:///opt/dremio/data/dist"
    }
    services: {
      coordinator.enabled: true
      executor.enabled: true
      coordinator.master.enabled: true
      coordinator.master.embedded-zookeeper.enabled: true
    }
  dremio-env: |
    DREMIO_MAX_HEAP_MEMORY_SIZE_MB=4096
    DREMIO_MAX_DIRECT_MEMORY_SIZE_MB=4096
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dremio
  namespace: dremio
spec:
  serviceName: dremio-cluster-pod
  replicas: 1
  selector:
    matchLabels:
      app: dremio
  template:
    metadata:
      labels:
        app: dremio
    spec:
      containers:
      - name: dremio
        image: dremio/dremio-oss:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DREMIO_MAX_HEAP_MEMORY_SIZE_MB
          value: "4096"
        - name: DREMIO_MAX_DIRECT_MEMORY_SIZE_MB
          value: "4096"
        ports:
        - containerPort: 9047
          name: web
        - containerPort: 31010
          name: client
        - containerPort: 45678
          name: server
        resources:
          requests:
            memory: 4Gi
            cpu: 1
          limits:
            memory: 8Gi
            cpu: 2
        volumeMounts:
        - name: dremio-config
          mountPath: /opt/dremio/conf
        - name: dremio-data
          mountPath: /opt/dremio/data
        livenessProbe:
          httpGet:
            path: /
            port: 9047
          initialDelaySeconds: 120
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 9047
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 3
      volumes:
      - name: dremio-config
        configMap:
          name: dremio-config
  volumeClaimTemplates:
  - metadata:
      name: dremio-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dremio-client
  namespace: dremio
spec:
  ports:
  - port: 9047
    targetPort: 9047
    name: web
  - port: 31010
    targetPort: 31010
    name: client
  - port: 32010
    targetPort: 45678
    name: flight
  selector:
    app: dremio
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dremio-cluster-pod
  namespace: dremio
spec:
  ports:
  - port: 9047
    targetPort: 9047
    name: web
  clusterIP: None
  selector:
    app: dremio