apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - prometheus/servicemonitor.yaml

helmCharts:
  - name: dremio-helm
    repo: oci://quay.io/dremio
    version: 3.0.1
    releaseName: dremio
    namespace: dremio
    valuesFile: values.yaml