# ServiceMonitor for Prometheus scraping
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dremio-metrics
  namespace: dremio
  labels:
    prometheus: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: dremio-coordinator
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics