# Fixed Dremio Values for Direct Helm Chart
# This properly disables MongoDB and other optional components

# License and image
dremio:
  license: "eyJraWQiOiI4MGZhMjgxYzZhZjczNDNkNTE1YTVhMzg1MDg1N2RhNmE2YmEzMTU3NWE5ZjVlZmVhMmQ4MTkyMGUyM2Q2OGY0IiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJEcmVtaW8iLCJzdWIiOiIwMDM1ZDAwMDA3TFRkT0VBQTEiLCJuYmYiOjE3NTI3ODA0NzYsImV4cCI6MTc1NTU0NTI3NiwiaWF0IjoxNzUyNzgwNDc2LCJqdGkiOiIxNzUyNzgwNDc2MDYyVzJjciJ9.u8bxfpQvyieeGn3H8RNIyKqbIgHR4pYO0mfBDBh23WJJw58t2WsDEhbOL6rUdfyGu4hItUtcohCoSEXMaAAolg"
  
  image:
    repository: quay.io/dremio/dremio-enterprise
    tag: 26.0.1

imagePullSecrets:
  - dremio-quay-secret

# Coordinator - with reduced resources
coordinator:
  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "2"
      memory: "8Gi"
  volumeSize: "50Gi"
  count: 0  # Secondary coordinators
  master:
    resources:
      requests:
        cpu: "2"
        memory: "8Gi"
      limits:
        cpu: "2"
        memory: "8Gi"
    volumeSize: "50Gi"
    count: 1  # Always 1 master

# Executor - with reduced resources
executor:
  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "2"
      memory: "8Gi"
  count: 1
  volumeSize: "50Gi"
  engines: ["default"]
  cloudCache:
    enabled: false

# Service
service:
  type: ClusterIP

# Zookeeper - with reduced resources
zookeeper:
  resources:
    requests:
      cpu: "0.5"
      memory: "1Gi"
    limits:
      cpu: "0.5"
      memory: "1Gi"
  volumeSize: "10Gi"
  count: 1

# MinIO Storage
distStorage:
  type: "aws"
  aws:
    bucketName: "dremio-dist-storage"
    path: "/"
    authentication: "accessKeySecret"
    credentials:
      accessKey: "minioadmin"
      secret: "minioadmin123"
    extraProperties: |
      <property>
        <n>fs.s3a.endpoint</n>
        <value>http://minio.minio.svc.cluster.local:9000</value>
      </property>
      <property>
        <n>fs.s3a.path.style.access</n>
        <value>true</value>
      </property>
      <property>
        <n>dremio.s3.compat</n>
        <value>true</value>
      </property>
      <property>
        <n>fs.s3a.connection.ssl.enabled</n>
        <value>false</value>
      </property>

# IMPORTANT: Properly disable MongoDB and other optional components
# These components are part of the new catalog architecture
mongodb:
  enabled: false

mongodbOperator:
  enabled: false

catalog:
  enabled: false

catalogservices:
  enabled: false

opensearch:
  enabled: false

nats:
  enabled: false

engineOperator:
  enabled: false

telemetry:
  enabled: false