# Ultra-Minimal Dremio Configuration
# Only essential components enabled

# License
dremio:
  license: "eyJraWQiOiI4MGZhMjgxYzZhZjczNDNkNTE1YTVhMzg1MDg1N2RhNmE2YmEzMTU3NWE5ZjVlZmVhMmQ4MTkyMGUyM2Q2OGY0IiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJEcmVtaW8iLCJzdWIiOiIwMDM1ZDAwMDA3TFRkT0VBQTEiLCJuYmYiOjE3NTI3ODA0NzYsImV4cCI6MTc1NTU0NTI3NiwiaWF0IjoxNzUyNzgwNDc2LCJqdGkiOiIxNzUyNzgwNDc2MDYyVzJjciJ9.u8bxfpQvyieeGn3H8RNIyKqbIgHR4pYO0mfBDBh23WJJw58t2WsDEhbOL6rUdfyGu4hItUtcohCoSEXMaAAolg"
  
  image:
    repository: quay.io/dremio/dremio-enterprise

# Image Pull Secret
imagePullSecrets:
  - i-bouabdallaoui-dataplatform-pull-secret

# Coordinator - Minimal
# In your dremio-values.yaml, add:
coordinator:
  resources:
    requests:
      cpu: "2"        # Minimum for testing
      memory: "8Gi"   # Minimum recommended
    limits:
      cpu: "2"
      memory: "8Gi"
  web:
    auth:
      enabled: true
      type: "internal"
    tls:
      enabled: false

# Service
service:
  type: ClusterIP
  sessionAffinity: "ClientIP"

# Zookeeper - Minimal
zookeeper:
  enabled: true
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"
  volumeSize: "5Gi"
  count: 1

# MinIO Storage
distStorage:
  type: "aws"
  aws:
    bucketName: "dremio-dist-storage"
    path: "/"
    authentication: "accessKeySecret"
    credentials:
      accessKey: "minioadmin"
      secret: "minioadmin123"
    extraProperties: |
      <property>
        <n>fs.s3a.endpoint</n>
        <value>http://minio.minio.svc.cluster.local:9000</value>
      </property>
      <property>
        <n>fs.s3a.path.style.access</n>
        <value>true</value>
      </property>

# Disable ALL optional components
mongodb:
  enabled: false

nats:
  enabled: false

catalog:
  enabled: false
  externalAccess:
    enabled: false

catalogExternalAccessServer:
  enabled: false

catalogServiceServer:
  enabled: false

engineOperator:
  enabled: false

# Add executor configuration
executor:
  enabled: true
  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "2"
      memory: "8Gi"
  count: 1
  volumeSize: 20Gi
  engines: ["default"]

opensearch:
  enabled: false

telemetry:
  enabled: false

ingress:
  enabled: false

# Essential labels
commonLabels:
  app: dremio
  app.kubernetes.io/name: dremio
  app.kubernetes.io/instance: dremio