# Dremio Helm Chart Values - Minimal Configuration for Testing
# This configuration uses minimal resources suitable for development/testing

# License and image
dremio:
  license: "eyJraWQiOiI4MGZhMjgxYzZhZjczNDNkNTE1YTVhMzg1MDg1N2RhNmE2YmEzMTU3NWE5ZjVlZmVhMmQ4MTkyMGUyM2Q2OGY0IiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJEcmVtaW8iLCJzdWIiOiIwMDM1ZDAwMDA3TFRkT0VBQTEiLCJuYmYiOjE3NTI3ODA0NzYsImV4cCI6MTc1NTU0NTI3NiwiaWF0IjoxNzUyNzgwNDc2LCJqdGkiOiIxNzUyNzgwNDc2MDYyVzJjciJ9.u8bxfpQvyieeGn3H8RNIyKqbIgHR4pYO0mfBDBh23WJJw58t2WsDEhbOL6rUdfyGu4hItUtcohCoSEXMaAAolg"
  
  image:
    repository: quay.io/dremio/dremio-enterprise
    tag: 26.0.1

imagePullSecrets:
  - dremio-quay-secret

# Minimal Coordinator (Master only)
coordinator:
  master:
    resources:
      requests:
        cpu: "2"         # Minimum viable
        memory: "8Gi"    # Minimum for stable operation
      limits:
        cpu: "2"
        memory: "8Gi"
    volumeSize: "50Gi"   # Smaller volume for testing
    count: 1
  
  # No secondary coordinators in minimal setup
  count: 0

# Minimal Executor
executor:
  resources:
    requests:
      cpu: "2"           # Minimum viable
      memory: "8Gi"      # Minimum for basic queries
    limits:
      cpu: "2"
      memory: "8Gi"
  count: 1               # Single executor for testing
  volumeSize: "50Gi"     # Smaller spill volume
  engines: ["default"]
  
  # No cloud cache in minimal setup
  cloudCache:
    enabled: false

# Service
service:
  type: ClusterIP

# Minimal Zookeeper
zookeeper:
  resources:
    requests:
      cpu: "0.5"         # Very light
      memory: "1Gi"      
    limits:
      cpu: "0.5"
      memory: "1Gi"
  volumeSize: "10Gi"
  count: 1               # Single node for testing

# MinIO Storage
distStorage:
  type: "aws"
  aws:
    bucketName: "dremio-dist-storage"
    path: "/"
    authentication: "accessKeySecret"
    credentials:
      accessKey: "minioadmin"
      secret: "minioadmin123"
    extraProperties: |
      <property>
        <n>fs.s3a.endpoint</n>
        <value>http://minio.minio.svc.cluster.local:9000</value>
      </property>
      <property>
        <n>fs.s3a.path.style.access</n>
        <value>true</value>
      </property>
      <property>
        <n>dremio.s3.compat</n>
        <value>true</value>
      </property>
      <property>
        <n>fs.s3a.connection.ssl.enabled</n>
        <value>false</value>
      </property>

engineOperator:
  enabled: false
  replicas: 0

catalog:
  enabled: false
  replicas: 0

catalogservices:
  enabled: false
  replicas: 0

mongodb:
  enabled: false
  replicas: 0

mongodbOperator:
  enabled: false
  replicas: 0

opensearch:
  enabled: false

nats:
  enabled: false
  replicas: 0

telemetry:
  enabled: false