# Explicit overrides for resource-constrained environment
# This file explicitly sets ALL resource values to prevent defaults

# License
dremio:
  license: "eyJraWQiOiI4MGZhMjgxYzZhZjczNDNkNTE1YTVhMzg1MDg1N2RhNmE2YmEzMTU3NWE5ZjVlZmVhMmQ4MTkyMGUyM2Q2OGY0IiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJEcmVtaW8iLCJzdWIiOiIwMDM1ZDAwMDA3TFRkT0VBQTEiLCJuYmYiOjE3NTI3ODA0NzYsImV4cCI6MTc1NTU0NTI3NiwiaWF0IjoxNzUyNzgwNDc2LCJqdGkiOiIxNzUyNzgwNDc2MDYyVzJjciJ9.u8bxfpQvyieeGn3H8RNIyKqbIgHR4pYO0mfBDBh23WJJw58t2WsDEhbOL6rUdfyGu4hItUtcohCoSEXMaAAolg"
  image:
    repository: quay.io/dremio/dremio-enterprise

imagePullSecrets:
  - name: dremio-pull-secret

# EXPLICITLY override engine operator resources
engineOperator:
  enabled: true
  image:
    repository: quay.io/dremio/dremio-engine-operator
  resources:
    requests:
      cpu: "250m"      # Reduced to be safe
      memory: "512Mi"  # Matching the apparent limit
    limits:
      cpu: "250m"
      memory: "512Mi"

# EXPLICITLY override coordinator
coordinator:
  resources:
    requests:
      cpu: "500m"
      memory: "4Gi"
    limits:
      cpu: "500m"
      memory: "4Gi"
  volumeSize: "100Gi"
  count: 0

# EXPLICITLY override catalog services
catalogServiceServer:
  enabled: true
  image:
    repository: quay.io/dremio/catalog-service-server
  resources:
    requests:
      cpu: "500m"      # NOT 4!
      memory: "2Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"

# EXPLICITLY override catalog external access
catalogExternalAccessServer:
  enabled: true
  image:
    repository: quay.io/dremio/catalog-external-access-server
  resources:
    requests:
      cpu: "500m"      # NOT 4!
      memory: "2Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"

# EXPLICITLY override catalog
catalog:
  enabled: true
  image:
    repository: quay.io/dremio/catalog-server
  resources:
    requests:
      cpu: "500m"      # NOT 4!
      memory: "2Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"

# MongoDB with explicit limits
mongodb:
  enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"
  volumeSize: "100Gi"
  replicas: 1

# Zookeeper with explicit limits
zookeeper:
  enabled: true
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"
  volumeSize: "10Gi"
  count: 1

# NATS with explicit limits
nats:
  enabled: true
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

# Service config
service:
  type: ClusterIP
  sessionAffinity: "ClientIP"

# Storage config
distStorage:
  type: "aws"
  aws:
    bucketName: "dremio-dist-storage"
    path: "/"
    authentication: "accessKeySecret"
    credentials:
      accessKey: "minioadmin"
      secret: "minioadmin123"
    extraProperties: |
      <property>
        <n>fs.s3a.endpoint</n>
        <value>http://minio.minio.svc.cluster.local:9000</value>
      </property>
      <property>
        <n>fs.s3a.path.style.access</n>
        <value>true</value>
      </property>

# Catalog storage
catalog:
  storage:
    type: "S3"
    location: "s3://dremio-catalog/catalog"
    s3:
      region: "us-east-1"
      useAccessKeys: true
    extraProperties: |
      <property>
        <n>fs.s3a.endpoint</n>
        <value>http://minio.minio.svc.cluster.local:9000</value>
      </property>
      <property>
        <n>fs.s3a.path.style.access</n>
        <value>true</value>
      </property>

# Disable non-essential components
opensearch:
  enabled: false

telemetry:
  enabled: false

ingress:
  enabled: false

# Ensure labels
commonLabels:
  app: dremio