# Dremio Enterprise Values - Resource Constrained Environment
# Adjusted for namespace limits: 500m CPU max, 100Gi storage max

# License Configuration (Required)
dremio:
  license: "eyJraWQiOiI4MGZhMjgxYzZhZjczNDNkNTE1YTVhMzg1MDg1N2RhNmE2YmEzMTU3NWE5ZjVlZmVhMmQ4MTkyMGUyM2Q2OGY0IiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJEcmVtaW8iLCJzdWIiOiIwMDM1ZDAwMDA3TFRkT0VBQTEiLCJuYmYiOjE3NTI3ODA0NzYsImV4cCI6MTc1NTU0NTI3NiwiaWF0IjoxNzUyNzgwNDc2LCJqdGkiOiIxNzUyNzgwNDc2MDYyVzJjciJ9.u8bxfpQvyieeGn3H8RNIyKqbIgHR4pYO0mfBDBh23WJJw58t2WsDEhbOL6rUdfyGu4hItUtcohCoSEXMaAAolg"
  
  # Enterprise Edition image
  image:
    repository: quay.io/dremio/dremio-enterprise

# Image Pull Secrets
imagePullSecrets:
  - name: dremio-pull-secret

# Coordinator Configuration - CONSTRAINED
coordinator:
  resources:
    requests:
      cpu: "500m"      # Maximum allowed
      memory: "8Gi"
    limits:
      cpu: "500m"      # Must match request
      memory: "8Gi"
  
  volumeSize: "100Gi"  # Maximum allowed
  count: 0             # Only primary coordinator
  
  # Web UI Configuration
  web:
    auth:
      enabled: true
      type: "internal"
    tls:
      enabled: false
  
  # Client Configuration
  client:
    tls:
      enabled: false
  
  # Flight Configuration  
  flight:
    tls:
      enabled: false

# Service Configuration
service:
  type: ClusterIP      # Use ingress instead of LoadBalancer
  sessionAffinity: "ClientIP"

# Ingress - Using your existing ingress
ingress:
  enabled: false       # Disabled because you have custom ingress

# Distributed Storage - MinIO
distStorage:
  type: "aws"
  aws:
    bucketName: "dremio-dist-storage"
    path: "/"
    authentication: "accessKeySecret"
    credentials:
      accessKey: "minioadmin"
      secret: "minioadmin123"
    extraProperties: |
      <property>
        <name>fs.s3a.endpoint</name>
        <value>http://minio.minio.svc.cluster.local:9000</value>
      </property>
      <property>
        <name>fs.s3a.path.style.access</name>
        <value>true</value>
      </property>
      <property>
        <name>dremio.s3.compat</name>
        <value>true</value>
      </property>

# Enterprise Catalog - MinIO
catalog:
  externalAccess:
    enabled: true
  
  storage:
    type: "S3"
    location: "s3://dremio-catalog/catalog"
    
    s3:
      region: "us-east-1"
      useAccessKeys: true
      
    extraProperties: |
      <property>
        <name>fs.s3a.endpoint</name>
        <value>http://minio.minio.svc.cluster.local:9000</value>
      </property>
      <property>
        <name>fs.s3a.path.style.access</name>
        <value>true</value>
      </property>

# OpenSearch - Disabled
opensearch:
  enabled: false
  replicas: 0

# MongoDB - CONSTRAINED
mongodb:
  resources:
    requests:
      cpu: "500m"      # Reduced from 8
      memory: "4Gi"    
    limits:
      cpu: "500m"
      memory: "4Gi"
  volumeSize: "100Gi"  # Maximum allowed
  replicas: 1          # Minimal for testing

# Zookeeper - CONSTRAINED
zookeeper:
  resources:
    requests:
      cpu: "500m"      # Already compliant
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  volumeSize: "10Gi"
  count: 1             # Minimal for testing

# NATS - CONSTRAINED
nats:
  resources:
    requests:
      cpu: "500m"      # Reduced from 700m
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Catalog Service - CONSTRAINED
catalog:
  resources:
    requests:
      cpu: "500m"      # Reduced from 4
      memory: "4Gi"    # Reduced from 8Gi
    limits:
      cpu: "500m"
      memory: "4Gi"

# Catalog External Access - CONSTRAINED
catalogExternalAccessServer:
  resources:
    requests:
      cpu: "500m"      # Reduced from 4
      memory: "4Gi"    # Reduced from 8Gi
    limits:
      cpu: "500m"      # Must be explicit
      memory: "4Gi"

# Catalog Service Server - CONSTRAINED
catalogServiceServer:
  resources:
    requests:
      cpu: "500m"      # Reduced from 4
      memory: "4Gi"    # Reduced from 8Gi
    limits:
      cpu: "500m"      # Must be explicit
      memory: "4Gi"

# Engine Operator - CONSTRAINED
engineOperator:
  resources:
    requests:
      cpu: "500m"      # Reduced from 1
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

# Engine Configuration
engine:
  options:
    resourceAllocationOffsets:
      defaultOffset: reserve-2-8

# Telemetry - Disabled initially
telemetry:
  enabled: false

# Labels for proper resource management
commonLabels:
  app: dremio
  app.kubernetes.io/part-of: data-platform
  
labels:
  app: dremio

# Global metadata
annotations: {}
tolerations: []
nodeSelector: {}